import json
import logging
from datetime import datetime, UTC
from typing import List, Optional, Tuple

from fastapi import BackgroundTasks, Depends, FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address
from sqlalchemy.orm import Session

from src.cddbs.config import settings
from src.cddbs.database import SessionLocal, init_db
from src.cddbs.models import (
    Outlet, Report, Briefing, NarrativeMatch, Feedback,
    TopicRun, TopicOutletResult,
    RawArticle, EventCluster, NarrativeBurst,
    WebhookConfig,
)
from src.cddbs.pipeline.orchestrator import run_pipeline
from src.cddbs.pipeline.topic_pipeline import run_topic_pipeline
from src.cddbs.narratives import get_all_narratives
from src.cddbs.webhooks import fire_event, SUPPORTED_EVENTS
from src.cddbs.api.security_headers import SecurityHeadersMiddleware
from src.cddbs.utils.input_sanitizer import (
    sanitize_topic, sanitize_outlet, sanitize_handle, sanitize_country,
)


from contextlib import asynccontextmanager

from src.cddbs.collectors.manager import CollectorManager

logger = logging.getLogger(__name__)

# Global collector manager instance
_collector_manager: CollectorManager | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _collector_manager
    # Ensure tables exist on startup
    init_db()

    # Start collector manager for event intelligence pipeline
    _collector_manager = CollectorManager(db_session_factory=SessionLocal)
    _collector_manager.start_background(interval_seconds=180)  # every 3 minutes

    yield

    # Shutdown collectors
    if _collector_manager:
        _collector_manager.stop()

app = FastAPI(title="CDDBS API", lifespan=lifespan)

# --- Rate Limiting (OWASP LLM04: Model Denial of Service) ---
limiter = Limiter(key_func=get_remote_address)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# --- Security Headers Middleware ---
app.add_middleware(SecurityHeadersMiddleware)

# --- CORS Hardening ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS,
    allow_credentials=False,
    allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers=["Content-Type"],
)


# --- Global Error Handler (sanitize error details) ---
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    """Catch unhandled exceptions and return sanitized error responses.
    Prevents leaking internal details (DB schema, stack traces) to clients.
    """
    logger.exception("Unhandled exception on %s %s", request.method, request.url.path)
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error"},
    )


def get_db():
    """Provide a SQLAlchemy session for request lifetime."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()



@app.get("/")
def root():
    return {"service": "cddbs", "status": "ok"}


# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------


class ArticleAnalysis(BaseModel):
    propaganda_score: Optional[float] = None
    sentiment: Optional[str] = None
    framing: Optional[str] = None
    key_claims: Optional[List[str]] = None
    key_actors: Optional[List[str]] = None
    narrative_themes: Optional[List[str]] = None
    unverified_statements: Optional[List[str]] = None
    analysis_notes: Optional[str] = None


class ArticleSummary(BaseModel):
    id: int
    title: str
    link: Optional[str] = None
    snippet: Optional[str] = None
    date: Optional[str] = None
    analysis: Optional[ArticleAnalysis] = None

    model_config = {
        "from_attributes": True
    }


class ReportData(BaseModel):
    outlet: str
    url: str
    country: str
    analysis_date: datetime
    articles_analyzed: int


class AIMetadata(BaseModel):
    """Machine-readable AI provenance — EU AI Act Art. 50 compliance."""
    model_id: str = "gemini-2.5-flash"
    prompt_version: Optional[str] = None
    generated_at: datetime
    quality_score: Optional[int] = None
    quality_rating: Optional[str] = None
    requires_human_review: bool = True
    disclosure: str = "This content was generated by an AI language model (Google Gemini). It requires review by a qualified human analyst before any operational use."


class ReportResponse(BaseModel):
    id: int
    outlet: str
    country: Optional[str] = None
    created_at: datetime
    meta: Optional[ReportData] = None
    final_report: Optional[str] = None
    tldr_summary: Optional[str] = None
    structured_briefing: Optional[dict] = None
    status: str
    message: Optional[str] = None
    articles: List[ArticleSummary] = Field(default_factory=list)
    ai_metadata: Optional[AIMetadata] = None


class RunCreateRequest(BaseModel):
    outlet: str
    url: str
    country: str
    num_articles: int = Field(5, ge=1, le=20)
    date_filter: Optional[str] = Field("m", description="Date filter for articles: h (hour), d (day), w (week), m (month), y (year)")


class RunStatusResponse(BaseModel):
    id: int
    outlet: str
    country: Optional[str] = None
    created_at: datetime
    status: str
    message: Optional[str] = None
    quality_score: Optional[int] = None
    quality_rating: Optional[str] = None
    narrative_count: Optional[int] = None


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _get_report_status(report: Report) -> Tuple[str, Optional[str]]:
    """Helper to determine the high-level status of a report."""
    status = "completed"
    msg = None
    data = report.data or {}
    errors = data.get("errors") if isinstance(data, dict) else None
    
    if errors:
        status = "failed"
        msg = "; ".join(map(str, errors))
    elif not report.final_report:
        status = "running"
        
    return status, msg


def _get_or_create_outlet(db: Session, name: str, url: str) -> Outlet:
    outlet = db.query(Outlet).filter(Outlet.name == name).first()
    if outlet:
        # Update URL if it changed
        if url and outlet.url != url:
            outlet.url = url
            db.add(outlet)
            db.commit()
            db.refresh(outlet)
        return outlet

    outlet = Outlet(name=name, url=url)
    db.add(outlet)
    db.commit()
    db.refresh(outlet)
    return outlet


def _run_analysis_job(
    report_id: int,
    outlet: str,
    url: str,
    country: str,
    num_articles: int = 5,
    date_filter: str = "m"
):
    """
    Background job that executes the analysis pipeline and persists results.
    """
    db = SessionLocal()
    try:
        # handle updating the report and articles
        run_pipeline(
            outlet,
            country,
            report_id=report_id,
            num_articles=num_articles,
            url=url,
            date_filter=date_filter
        )

    except Exception as exc:  # noqa: BLE001
        # If something fails, we still want the report row to exist; we just
        # store the error message in its data payload.
        report = db.query(Report).filter(Report.id == report_id).first()
        if report:
            report.data = {
                "outlet": outlet,
                "url": url,
                "country": country,
                "analysis_date": datetime.now(UTC).isoformat(),
                "articles_analyzed": 0,
                "errors": [str(exc)],
            }
            db.add(report)
            db.commit()
    finally:
        db.close()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


@app.post("/analysis-runs", response_model=RunStatusResponse)
@limiter.limit("5/minute")
def create_analysis_run(
    request: Request,
    payload: RunCreateRequest,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
):
    """
    Create a new analysis run.

    This immediately creates a placeholder Report row and then schedules
    the long-running analysis in a background task.
    """
    # Sanitize user-provided inputs (OWASP LLM01)
    clean_outlet = sanitize_outlet(payload.outlet)
    clean_country = sanitize_country(payload.country)

    report = Report(
        outlet=clean_outlet,
        country=clean_country,
        final_report=None,
        data={
            "outlet": clean_outlet,
            "url": payload.url,
            "country": clean_country,
            "analysis_date": datetime.now(UTC).isoformat(),
            "articles_analyzed": 0,
            "status": "pending",
        },
    )
    db.add(report)
    db.commit()
    db.refresh(report)

    background_tasks.add_task(
        _run_analysis_job,
        report_id=report.id,
        outlet=clean_outlet,
        url=payload.url,
        country=clean_country,
        num_articles=payload.num_articles,
        date_filter=payload.date_filter or "m"
    )

    return RunStatusResponse(
        id=report.id,
        outlet=report.outlet,
        country=report.country,
        created_at=report.created_at,
        status="queued",
        message="Analysis run scheduled",
    )


@app.get("/analysis-runs", response_model=List[RunStatusResponse])
def list_analysis_runs(db: Session = Depends(get_db)):
    """Return a lightweight list of analysis runs for the UI history view."""
    reports = db.query(Report).order_by(Report.created_at.desc()).all()
    response: List[RunStatusResponse] = []

    for r in reports:
        status, msg = _get_report_status(r)
        data = r.data or {}
        response.append(
            RunStatusResponse(
                id=r.id,
                outlet=r.outlet,
                country=r.country,
                created_at=r.created_at,
                status=status,
                message=msg,
                quality_score=data.get("quality_score") if isinstance(data, dict) else None,
                quality_rating=data.get("quality_rating") if isinstance(data, dict) else None,
                narrative_count=data.get("narrative_matches_count") if isinstance(data, dict) else None,
            )
        )

    return response


@app.get("/analysis-runs/{report_id}", response_model=ReportResponse)
def get_analysis_run(report_id: int, db: Session = Depends(get_db)):
    """
    Return a single analysis run, including its final report text and
    a list of associated articles (if any).

    This endpoint is what the frontend will use for the detailed briefing view.
    """
    report = db.query(Report).filter(Report.id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    data = report.data or {}
    meta = None
    if isinstance(data, dict):
        try:
            meta = ReportData(
                outlet=data.get("outlet", report.outlet),
                url=data.get("url", ""),
                country=data.get("country", report.country or ""),
                analysis_date=datetime.fromisoformat(
                    data.get("analysis_date", datetime.now(UTC).isoformat())
                ),
                articles_analyzed=data.get("articles_analyzed", 0),
            )
        except Exception:  # noqa: BLE001
            meta = None

    # Return articles linked to this specific report with per-article analysis
    article_summaries: List[ArticleSummary] = []
    for a in report.articles:
        analysis_data = None
        if isinstance(a.meta, dict) and "analysis" in a.meta:
            try:
                analysis_data = ArticleAnalysis(**a.meta["analysis"])
            except Exception:
                analysis_data = None
        article_summaries.append(ArticleSummary(
            id=a.id,
            title=a.title,
            link=a.link,
            snippet=a.snippet,
            date=a.date,
            analysis=analysis_data,
        ))

    status, msg = _get_report_status(report)

    # Extract structured briefing and tldr from report data
    structured_briefing = None
    tldr_summary = None
    if isinstance(data, dict):
        structured_briefing = data.get("structured_briefing")
        tldr_summary = data.get("tldr_summary")

    # Also try to extract from raw_response JSON if not in data
    if not structured_briefing and report.raw_response:
        try:
            import re as _re
            _json_match = _re.search(r'(\{.*\})', report.raw_response, _re.DOTALL)
            if _json_match:
                _parsed = json.loads(_json_match.group(1))
                structured_briefing = structured_briefing or _parsed.get("structured_briefing")
                tldr_summary = tldr_summary or _parsed.get("tldr_summary")
        except Exception:
            pass

    # Build AI provenance metadata for EU AI Act Art. 50 compliance
    briefing_obj = report.briefing if hasattr(report, "briefing") else None
    ai_metadata = AIMetadata(
        generated_at=report.created_at,
        prompt_version=briefing_obj.prompt_version if briefing_obj else "v1.3",
        quality_score=briefing_obj.quality_score if briefing_obj else None,
        quality_rating=briefing_obj.quality_rating if briefing_obj else None,
    )

    return ReportResponse(
        id=report.id,
        outlet=report.outlet,
        country=report.country,
        created_at=report.created_at,
        meta=meta,
        final_report=report.final_report,
        tldr_summary=tldr_summary,
        structured_briefing=structured_briefing,
        status=status,
        message=msg,
        articles=article_summaries,
        ai_metadata=ai_metadata,
    )


@app.get("/health")
def healthcheck(db: Session = Depends(get_db)):
    """
    Lightweight health endpoint for deployment checks.
    Verifies DB connectivity in addition to the base service status.
    """
    try:
        from sqlalchemy import text
        db.execute(text("SELECT 1"))
    except Exception as exc:  # noqa: BLE001
        logger.error("Health check DB failure: %s", exc)
        raise HTTPException(status_code=500, detail="database_error") from exc

    return {"status": "ok"}


# ---------------------------------------------------------------------------
# Sprint 4: Quality & Narrative Endpoints
# ---------------------------------------------------------------------------


class QualityDimension(BaseModel):
    score: int
    max: int
    issues: List[str] = Field(default_factory=list)


class QualityResponse(BaseModel):
    report_id: int
    total_score: Optional[int] = None
    max_score: int = 70
    rating: Optional[str] = None
    dimensions: Optional[dict] = None
    prompt_version: Optional[str] = None


class NarrativeMatchResponse(BaseModel):
    id: int
    narrative_id: str
    narrative_name: str
    category: Optional[str] = None
    confidence: Optional[str] = None
    matched_keywords: Optional[List[str]] = None
    match_count: int = 0

    model_config = {
        "from_attributes": True
    }


class NarrativeInfoResponse(BaseModel):
    id: str
    name: str
    category_id: str
    category_name: str
    description: str
    keywords: List[str] = Field(default_factory=list)
    frequency: str = "unknown"
    active: bool = True


@app.get("/analysis-runs/{report_id}/quality", response_model=QualityResponse)
def get_quality_score(report_id: int, db: Session = Depends(get_db)):
    """Return the quality scorecard for a completed analysis run."""
    report = db.query(Report).filter(Report.id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    briefing = db.query(Briefing).filter(Briefing.report_id == report_id).first()
    if not briefing:
        return QualityResponse(
            report_id=report_id,
            total_score=None,
            rating=None,
            dimensions=None,
            prompt_version=None,
        )

    return QualityResponse(
        report_id=report_id,
        total_score=briefing.quality_score,
        max_score=70,
        rating=briefing.quality_rating,
        dimensions=briefing.quality_details.get("dimensions") if briefing.quality_details else None,
        prompt_version=briefing.prompt_version,
    )


@app.get("/analysis-runs/{report_id}/narratives", response_model=List[NarrativeMatchResponse])
def get_narrative_matches(report_id: int, db: Session = Depends(get_db)):
    """Return narrative matches for a completed analysis run."""
    report = db.query(Report).filter(Report.id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    matches = db.query(NarrativeMatch).filter(
        NarrativeMatch.report_id == report_id
    ).order_by(NarrativeMatch.match_count.desc()).all()

    return [
        NarrativeMatchResponse(
            id=m.id,
            narrative_id=m.narrative_id,
            narrative_name=m.narrative_name,
            category=m.category,
            confidence=m.confidence,
            matched_keywords=m.matched_keywords,
            match_count=m.match_count,
        )
        for m in matches
    ]


@app.get("/narratives", response_model=List[NarrativeInfoResponse])
def list_narratives():
    """Return the full known narratives database (for reference/UI display)."""
    return [NarrativeInfoResponse(**n) for n in get_all_narratives()]


# ---------------------------------------------------------------------------
# Feedback (standalone, no relationships)
# ---------------------------------------------------------------------------


class FeedbackCreateRequest(BaseModel):
    tester_name: Optional[str] = None
    tester_role: Optional[str] = None
    overall_rating: int = Field(..., ge=1, le=5)
    accuracy_rating: int = Field(..., ge=1, le=5)
    usability_rating: int = Field(..., ge=1, le=5)
    bugs_encountered: str = Field(..., min_length=5)
    misleading_outputs: Optional[str] = None
    missing_features: Optional[str] = None
    ux_pain_points: Optional[str] = None
    professional_concerns: Optional[str] = None
    would_recommend: Optional[str] = None
    additional_comments: Optional[str] = None


class FeedbackResponse(BaseModel):
    id: int
    tester_name: Optional[str] = None
    tester_role: Optional[str] = None
    overall_rating: int
    accuracy_rating: int
    usability_rating: int
    bugs_encountered: str
    misleading_outputs: Optional[str] = None
    missing_features: Optional[str] = None
    ux_pain_points: Optional[str] = None
    professional_concerns: Optional[str] = None
    would_recommend: Optional[str] = None
    additional_comments: Optional[str] = None
    created_at: datetime

    model_config = {"from_attributes": True}


@app.post("/feedback", response_model=FeedbackResponse)
def submit_feedback(payload: FeedbackCreateRequest, db: Session = Depends(get_db)):
    """Submit tester feedback (early-stage quality gate)."""
    fb = Feedback(
        tester_name=payload.tester_name,
        tester_role=payload.tester_role,
        overall_rating=payload.overall_rating,
        accuracy_rating=payload.accuracy_rating,
        usability_rating=payload.usability_rating,
        bugs_encountered=payload.bugs_encountered,
        misleading_outputs=payload.misleading_outputs,
        missing_features=payload.missing_features,
        ux_pain_points=payload.ux_pain_points,
        professional_concerns=payload.professional_concerns,
        would_recommend=payload.would_recommend,
        additional_comments=payload.additional_comments,
    )
    db.add(fb)
    db.commit()
    db.refresh(fb)
    return fb


@app.get("/feedback", response_model=List[FeedbackResponse])
def list_feedback(db: Session = Depends(get_db)):
    """List all feedback entries (for dev review)."""
    return db.query(Feedback).order_by(Feedback.created_at.desc()).all()


# ---------------------------------------------------------------------------
# Monitoring Dashboard Stats Endpoints
# ---------------------------------------------------------------------------


class GlobalStatsResponse(BaseModel):
    total_analyses: int
    countries_monitored: int
    total_narratives_detected: int
    active_runs: int
    completed_runs: int
    failed_runs: int
    avg_quality_score: Optional[float] = None
    # Event intelligence pipeline stats
    active_events: int = 0
    active_bursts: int = 0
    articles_ingested: int = 0


class CountryStatItem(BaseModel):
    country: str
    run_count: int
    completed_count: int
    narrative_count: int
    avg_quality: Optional[float] = None
    risk_score: float  # composite score for map coloring


class NarrativeTrendItem(BaseModel):
    narrative_id: str
    narrative_name: str
    category: Optional[str]
    total_matches: int
    report_count: int
    confidence_high: int
    confidence_medium: int
    confidence_low: int


class FeedItem(BaseModel):
    title: str
    url: str
    domain: str
    source_country: Optional[str]
    published: str
    language: str


class MonitoringFeedResponse(BaseModel):
    items: List[FeedItem]
    source: str
    fetched_at: str
    error: Optional[str] = None


@app.get("/stats/global", response_model=GlobalStatsResponse)
def get_global_stats(db: Session = Depends(get_db)):
    """Aggregate global stats for the monitoring dashboard metric bar."""

    reports = db.query(Report).all()
    total = len(reports)

    countries = set()
    active = 0
    completed = 0
    failed = 0
    quality_scores = []
    narrative_total = 0

    for r in reports:
        if r.country:
            countries.add(r.country)
        status, _ = _get_report_status(r)
        if status in ("running", "queued"):
            active += 1
        elif status == "completed":
            completed += 1
        elif status == "failed":
            failed += 1
        data = r.data or {}
        if isinstance(data, dict) and data.get("quality_score"):
            quality_scores.append(data["quality_score"])
        narrative_total += db.query(NarrativeMatch).filter(
            NarrativeMatch.report_id == r.id
        ).count()

    avg_quality = round(sum(quality_scores) / len(quality_scores), 1) if quality_scores else None

    # Event intelligence pipeline counts
    active_events = db.query(EventCluster).filter_by(status="active").count()
    active_bursts = db.query(NarrativeBurst).filter(NarrativeBurst.resolved_at == None).count()
    articles_ingested = db.query(RawArticle).count()

    return GlobalStatsResponse(
        total_analyses=total,
        countries_monitored=len(countries),
        total_narratives_detected=narrative_total,
        active_runs=active,
        completed_runs=completed,
        failed_runs=failed,
        avg_quality_score=avg_quality,
        active_events=active_events,
        active_bursts=active_bursts,
        articles_ingested=articles_ingested,
    )


@app.get("/stats/by-country", response_model=List[CountryStatItem])
def get_stats_by_country(db: Session = Depends(get_db)):
    """Per-country roll-up for the world map and country risk index."""
    from collections import defaultdict

    reports = db.query(Report).all()
    country_data: dict = defaultdict(lambda: {
        "run_count": 0, "completed": 0, "narratives": 0, "quality_scores": []
    })

    for r in reports:
        country = r.country or "Unknown"
        country_data[country]["run_count"] += 1
        status, _ = _get_report_status(r)
        if status == "completed":
            country_data[country]["completed"] += 1
        data = r.data or {}
        if isinstance(data, dict) and data.get("quality_score"):
            country_data[country]["quality_scores"].append(data["quality_score"])
        n_count = db.query(NarrativeMatch).filter(NarrativeMatch.report_id == r.id).count()
        country_data[country]["narratives"] += n_count

    results = []
    for country, d in country_data.items():
        if country == "Unknown":
            continue
        avg_q = round(sum(d["quality_scores"]) / len(d["quality_scores"]), 1) if d["quality_scores"] else None
        # Risk score: more narratives relative to runs = higher risk (0-100)
        narrative_ratio = (d["narratives"] / max(d["run_count"], 1)) * 20
        risk_score = min(100.0, round(narrative_ratio + (d["run_count"] * 5), 1))
        results.append(CountryStatItem(
            country=country,
            run_count=d["run_count"],
            completed_count=d["completed"],
            narrative_count=d["narratives"],
            avg_quality=avg_q,
            risk_score=risk_score,
        ))

    results.sort(key=lambda x: x.risk_score, reverse=True)
    return results


@app.get("/stats/narrative-trends", response_model=List[NarrativeTrendItem])
def get_narrative_trends(db: Session = Depends(get_db)):
    """Top narratives by frequency across all analyses."""
    from collections import defaultdict

    matches = db.query(NarrativeMatch).all()
    trends: dict = defaultdict(lambda: {
        "name": "", "category": None, "total": 0, "reports": set(),
        "high": 0, "medium": 0, "low": 0
    })

    for m in matches:
        t = trends[m.narrative_id]
        t["name"] = m.narrative_name
        t["category"] = m.category
        t["total"] += m.match_count
        t["reports"].add(m.report_id)
        conf = (m.confidence or "").lower()
        if conf == "high":
            t["high"] += 1
        elif conf == "medium":
            t["medium"] += 1
        else:
            t["low"] += 1

    results = [
        NarrativeTrendItem(
            narrative_id=nid,
            narrative_name=d["name"],
            category=d["category"],
            total_matches=d["total"],
            report_count=len(d["reports"]),
            confidence_high=d["high"],
            confidence_medium=d["medium"],
            confidence_low=d["low"],
        )
        for nid, d in trends.items()
    ]
    results.sort(key=lambda x: x.total_matches, reverse=True)
    return results[:15]


@app.get("/monitoring/feed", response_model=MonitoringFeedResponse)
def get_monitoring_feed(
    source_type: Optional[str] = None,
    limit: int = 50,
    db: Session = Depends(get_db),
):
    """Return recent articles from the multi-source collector pipeline."""

    query = db.query(RawArticle).filter(
        RawArticle.is_duplicate == False,
    )

    if source_type:
        query = query.filter(RawArticle.source_type == source_type)

    articles = (
        query.order_by(RawArticle.created_at.desc())
        .limit(limit)
        .all()
    )

    items = []
    for a in articles:
        published = ""
        if a.published_at:
            published = a.published_at.strftime("%Y-%m-%dT%H:%M:%SZ")
        elif a.created_at:
            published = a.created_at.strftime("%Y-%m-%dT%H:%M:%SZ")

        items.append(FeedItem(
            title=a.title or "No title",
            url=a.url or "",
            domain=a.source_domain or "",
            source_country=a.country,
            published=published,
            language=a.language or "en",
        ))

    source_label = f"Multi-source ({source_type})" if source_type else "Multi-source (RSS + GDELT)"

    return MonitoringFeedResponse(
        items=items,
        source=source_label,
        fetched_at=datetime.now(UTC).isoformat(),
    )


# ---------------------------------------------------------------------------
# Topic Mode endpoints
# ---------------------------------------------------------------------------


class TopicRunCreateRequest(BaseModel):
    topic: str = Field(..., min_length=3, max_length=300)
    num_outlets: int = Field(5, ge=1, le=10)
    date_filter: Optional[str] = Field("m", description="qdr: h/d/w/m/y")


class TopicRunStatusResponse(BaseModel):
    id: int
    topic: str
    num_outlets: int
    date_filter: str
    status: str
    created_at: datetime
    completed_at: Optional[datetime] = None
    error: Optional[str] = None
    outlets_found: int = 0


class TopicOutletResultResponse(BaseModel):
    id: int
    outlet_name: str
    outlet_domain: Optional[str] = None
    articles_analyzed: int
    divergence_score: Optional[int] = None
    amplification_signal: Optional[str] = None
    propaganda_techniques: Optional[List[str]] = None
    framing_summary: Optional[str] = None
    divergence_explanation: Optional[str] = None
    key_claims: Optional[List[str]] = None
    omissions: Optional[List[str]] = None
    article_links: Optional[List[dict]] = None

    model_config = {"from_attributes": True}


class TopicRunDetailResponse(TopicRunStatusResponse):
    baseline_summary: Optional[str] = None
    coordination_signal: Optional[float] = None
    coordination_detail: Optional[dict] = None
    outlet_results: List[TopicOutletResultResponse] = Field(default_factory=list)


def _run_topic_job(
    topic_run_id: int,
    topic: str,
    num_outlets: int,
    date_filter: str,
):
    """Background wrapper for run_topic_pipeline with error handling."""
    db = SessionLocal()
    try:
        run_topic_pipeline(
            topic_run_id=topic_run_id,
            topic=topic,
            num_outlets=num_outlets,
            date_filter=date_filter,
        )
    except Exception as exc:
        topic_run = db.query(TopicRun).filter(TopicRun.id == topic_run_id).first()
        if topic_run:
            topic_run.status = "failed"
            topic_run.error = str(exc)
            db.commit()
    finally:
        db.close()


@app.post("/topic-runs", response_model=TopicRunStatusResponse)
@limiter.limit("3/minute")
def create_topic_run(
    request: Request,
    payload: TopicRunCreateRequest,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
):
    """Create a new topic-mode analysis run."""
    # Sanitize user-provided topic (OWASP LLM01)
    clean_topic = sanitize_topic(payload.topic)

    topic_run = TopicRun(
        topic=clean_topic,
        num_outlets=payload.num_outlets,
        date_filter=payload.date_filter or "m",
        status="pending",
    )
    db.add(topic_run)
    db.commit()
    db.refresh(topic_run)

    background_tasks.add_task(
        _run_topic_job,
        topic_run_id=topic_run.id,
        topic=clean_topic,
        num_outlets=payload.num_outlets,
        date_filter=payload.date_filter or "m",
    )

    return TopicRunStatusResponse(
        id=topic_run.id,
        topic=topic_run.topic,
        num_outlets=topic_run.num_outlets,
        date_filter=topic_run.date_filter,
        status="pending",
        created_at=topic_run.created_at,
        outlets_found=0,
    )


@app.get("/topic-runs", response_model=List[TopicRunStatusResponse])
def list_topic_runs(db: Session = Depends(get_db)):
    """Return all topic runs ordered by creation date."""
    runs = db.query(TopicRun).order_by(TopicRun.created_at.desc()).all()
    result = []
    for r in runs:
        outlets_found = db.query(TopicOutletResult).filter(
            TopicOutletResult.topic_run_id == r.id
        ).count()
        result.append(TopicRunStatusResponse(
            id=r.id,
            topic=r.topic,
            num_outlets=r.num_outlets,
            date_filter=r.date_filter,
            status=r.status,
            created_at=r.created_at,
            completed_at=r.completed_at,
            error=r.error,
            outlets_found=outlets_found,
        ))
    return result


@app.get("/topic-runs/{topic_run_id}", response_model=TopicRunDetailResponse)
def get_topic_run(topic_run_id: int, db: Session = Depends(get_db)):
    """Return a topic run with its full outlet results ranked by divergence score."""
    topic_run = db.query(TopicRun).filter(TopicRun.id == topic_run_id).first()
    if not topic_run:
        raise HTTPException(status_code=404, detail="Topic run not found")

    results = (
        db.query(TopicOutletResult)
        .filter(TopicOutletResult.topic_run_id == topic_run_id)
        .order_by(TopicOutletResult.divergence_score.desc())
        .all()
    )

    outlet_responses = [
        TopicOutletResultResponse(
            id=r.id,
            outlet_name=r.outlet_name,
            outlet_domain=r.outlet_domain,
            articles_analyzed=r.articles_analyzed,
            divergence_score=r.divergence_score,
            amplification_signal=r.amplification_signal,
            propaganda_techniques=r.propaganda_techniques,
            framing_summary=r.framing_summary,
            divergence_explanation=r.divergence_explanation,
            key_claims=r.key_claims,
            omissions=r.omissions,
            article_links=r.article_links,
        )
        for r in results
    ]

    return TopicRunDetailResponse(
        id=topic_run.id,
        topic=topic_run.topic,
        num_outlets=topic_run.num_outlets,
        date_filter=topic_run.date_filter,
        status=topic_run.status,
        created_at=topic_run.created_at,
        completed_at=topic_run.completed_at,
        error=topic_run.error,
        outlets_found=len(results),
        baseline_summary=topic_run.baseline_summary,
        coordination_signal=topic_run.coordination_signal,
        coordination_detail=topic_run.coordination_detail,
        outlet_results=outlet_responses,
    )


# ---------------------------------------------------------------------------
# Event Intelligence Pipeline endpoints
# ---------------------------------------------------------------------------


class EventClusterResponse(BaseModel):
    id: int
    title: Optional[str] = None
    event_type: Optional[str] = None
    countries: Optional[list] = None
    keywords: Optional[list] = None
    first_seen: Optional[datetime] = None
    last_seen: Optional[datetime] = None
    article_count: int = 0
    source_count: int = 0
    burst_score: float = 0.0
    narrative_risk_score: float = 0.0
    status: str = "active"
    created_at: Optional[datetime] = None

    model_config = {"from_attributes": True}


class EventClusterDetailResponse(EventClusterResponse):
    entities: Optional[dict] = None
    articles: list[dict] = Field(default_factory=list)


class NarrativeBurstResponse(BaseModel):
    id: int
    keyword: str
    baseline_frequency: Optional[float] = None
    current_frequency: Optional[float] = None
    z_score: Optional[float] = None
    cluster_id: Optional[int] = None
    detected_at: Optional[datetime] = None
    resolved_at: Optional[datetime] = None

    model_config = {"from_attributes": True}


class CollectorStatusResponse(BaseModel):
    collectors: list[dict]


class EventMapItem(BaseModel):
    country: str
    event_count: int
    avg_risk_score: float
    top_event_type: Optional[str] = None


@app.get("/events", response_model=List[EventClusterResponse])
def list_events(
    event_type: Optional[str] = None,
    country: Optional[str] = None,
    status: Optional[str] = "active",
    min_risk: Optional[float] = None,
    limit: int = 50,
    offset: int = 0,
    db: Session = Depends(get_db),
):
    """List event clusters with optional filtering."""
    query = db.query(EventCluster)

    if status:
        query = query.filter(EventCluster.status == status)
    if event_type:
        query = query.filter(EventCluster.event_type == event_type)
    if min_risk is not None:
        query = query.filter(EventCluster.narrative_risk_score >= min_risk)
    if country:
        # JSON array contains check
        query = query.filter(EventCluster.countries.contains([country]))

    events = (
        query.order_by(EventCluster.narrative_risk_score.desc())
        .offset(offset)
        .limit(limit)
        .all()
    )

    return [EventClusterResponse.model_validate(e) for e in events]


@app.get("/events/map", response_model=List[EventMapItem])
def get_events_map(db: Session = Depends(get_db)):
    """Get events grouped by country for map visualization."""
    clusters = db.query(EventCluster).filter_by(status="active").all()

    country_data: dict[str, dict] = {}
    for cluster in clusters:
        for country in (cluster.countries or []):
            if country not in country_data:
                country_data[country] = {"events": [], "types": []}
            country_data[country]["events"].append(cluster)
            if cluster.event_type:
                country_data[country]["types"].append(cluster.event_type)

    result = []
    for country, data in country_data.items():
        events = data["events"]
        avg_risk = sum(e.narrative_risk_score or 0 for e in events) / len(events) if events else 0
        from collections import Counter
        type_counts = Counter(data["types"])
        top_type = type_counts.most_common(1)[0][0] if type_counts else None

        result.append(EventMapItem(
            country=country,
            event_count=len(events),
            avg_risk_score=round(avg_risk, 3),
            top_event_type=top_type,
        ))

    return sorted(result, key=lambda x: x.event_count, reverse=True)


@app.get("/events/bursts", response_model=List[NarrativeBurstResponse])
def list_bursts(
    min_zscore: Optional[float] = None,
    active_only: bool = True,
    limit: int = 50,
    db: Session = Depends(get_db),
):
    """List detected narrative bursts (keyword frequency spikes)."""
    query = db.query(NarrativeBurst)

    if active_only:
        query = query.filter(NarrativeBurst.resolved_at == None)
    if min_zscore is not None:
        query = query.filter(NarrativeBurst.z_score >= min_zscore)

    bursts = (
        query.order_by(NarrativeBurst.z_score.desc())
        .limit(limit)
        .all()
    )

    return [NarrativeBurstResponse.model_validate(b) for b in bursts]


@app.get("/events/{event_id}", response_model=EventClusterDetailResponse)
def get_event_detail(event_id: int, db: Session = Depends(get_db)):
    """Get detailed event cluster with articles."""
    cluster = db.query(EventCluster).filter(EventCluster.id == event_id).first()
    if not cluster:
        raise HTTPException(status_code=404, detail="Event cluster not found")

    articles = (
        db.query(RawArticle)
        .filter(RawArticle.cluster_id == event_id, RawArticle.is_duplicate == False)
        .order_by(RawArticle.published_at.desc())
        .limit(100)
        .all()
    )

    article_dicts = [
        {
            "id": a.id,
            "title": a.title,
            "url": a.url,
            "source_name": a.source_name,
            "source_domain": a.source_domain,
            "source_type": a.source_type,
            "published_at": a.published_at.isoformat() if a.published_at else None,
            "country": a.country,
        }
        for a in articles
    ]

    return EventClusterDetailResponse(
        id=cluster.id,
        title=cluster.title,
        event_type=cluster.event_type,
        countries=cluster.countries,
        keywords=cluster.keywords,
        entities=cluster.entities,
        first_seen=cluster.first_seen,
        last_seen=cluster.last_seen,
        article_count=cluster.article_count,
        source_count=cluster.source_count,
        burst_score=cluster.burst_score,
        narrative_risk_score=cluster.narrative_risk_score,
        status=cluster.status,
        created_at=cluster.created_at,
        articles=article_dicts,
    )


@app.get("/collector/status", response_model=CollectorStatusResponse)
def get_collector_status():
    """Get health status of all news collectors."""
    if _collector_manager:
        return CollectorStatusResponse(collectors=_collector_manager.statuses)
    return CollectorStatusResponse(collectors=[])


# ---------------------------------------------------------------------------
# v1.2 Charts: Activity Timeline & Narrative Frequency
# ---------------------------------------------------------------------------


class TimelineBucket(BaseModel):
    hour: str  # ISO-formatted hour, e.g. "2026-03-09T14:00:00"
    count: int
    rss: int = 0
    gdelt: int = 0


class NarrativeFrequencyItem(BaseModel):
    narrative_name: str
    category: Optional[str] = None
    total_matches: int
    high: int = 0
    medium: int = 0
    low: int = 0


@app.get("/stats/activity-timeline", response_model=List[TimelineBucket])
def get_activity_timeline(
    hours: int = 48,
    db: Session = Depends(get_db),
):
    """Article ingestion count grouped by hour for the last N hours."""
    from datetime import timedelta
    from sqlalchemy import func, case

    cutoff = datetime.now(UTC) - timedelta(hours=hours)

    # Group by hour using date_trunc
    rows = (
        db.query(
            func.date_trunc("hour", RawArticle.created_at).label("hour"),
            func.count().label("count"),
            func.sum(case((RawArticle.source_type == "rss", 1), else_=0)).label("rss"),
            func.sum(case((RawArticle.source_type == "gdelt", 1), else_=0)).label("gdelt"),
        )
        .filter(RawArticle.created_at >= cutoff)
        .group_by(func.date_trunc("hour", RawArticle.created_at))
        .order_by(func.date_trunc("hour", RawArticle.created_at))
        .all()
    )

    return [
        TimelineBucket(
            hour=row.hour.isoformat() if row.hour else "",
            count=row.count,
            rss=row.rss or 0,
            gdelt=row.gdelt or 0,
        )
        for row in rows
    ]


@app.get("/stats/narrative-frequency", response_model=List[NarrativeFrequencyItem])
def get_narrative_frequency(
    limit: int = 15,
    db: Session = Depends(get_db),
):
    """Top narratives by match count, with confidence breakdown for bar chart."""
    from collections import defaultdict

    matches = db.query(NarrativeMatch).all()
    narr_data: dict = defaultdict(lambda: {
        "name": "", "category": None, "total": 0,
        "high": 0, "medium": 0, "low": 0,
    })

    for m in matches:
        d = narr_data[m.narrative_id]
        d["name"] = m.narrative_name
        d["category"] = m.category
        d["total"] += m.match_count
        conf = (m.confidence or "").lower()
        if conf == "high":
            d["high"] += 1
        elif conf == "medium":
            d["medium"] += 1
        else:
            d["low"] += 1

    items = [
        NarrativeFrequencyItem(
            narrative_name=d["name"],
            category=d["category"],
            total_matches=d["total"],
            high=d["high"],
            medium=d["medium"],
            low=d["low"],
        )
        for d in narr_data.values()
        if d["total"] > 0
    ]
    items.sort(key=lambda x: x.total_matches, reverse=True)
    return items[:limit]


# ---------------------------------------------------------------------------
# v1.3 Network Graph: Outlet relationship network
# ---------------------------------------------------------------------------


class NetworkNode(BaseModel):
    id: str
    label: str
    type: str = "outlet"  # outlet / narrative / event
    size: int = 1
    color: Optional[str] = None


class NetworkEdge(BaseModel):
    source: str
    target: str
    weight: int = 1
    label: Optional[str] = None


class NetworkGraphResponse(BaseModel):
    nodes: List[NetworkNode]
    edges: List[NetworkEdge]


@app.get("/stats/outlet-network", response_model=NetworkGraphResponse)
def get_outlet_network(db: Session = Depends(get_db)):
    """Build an outlet relationship network from shared narrative matches.

    Outlets that amplify the same narratives get connected. Edge weight
    reflects the number of shared narratives.
    """
    from collections import defaultdict

    # Gather which outlets have which narratives
    reports = db.query(Report).filter(Report.final_report.isnot(None)).all()
    outlet_narratives: dict[str, set[str]] = defaultdict(set)
    outlet_report_count: dict[str, int] = defaultdict(int)

    for r in reports:
        if not r.outlet:
            continue
        outlet_report_count[r.outlet] += 1
        matches = db.query(NarrativeMatch).filter(
            NarrativeMatch.report_id == r.id
        ).all()
        for m in matches:
            outlet_narratives[r.outlet].add(m.narrative_id)

    # Build nodes for outlets with at least 1 narrative
    nodes: list[NetworkNode] = []
    outlet_ids: set[str] = set()
    for outlet, narrs in outlet_narratives.items():
        if narrs:
            outlet_ids.add(outlet)
            nodes.append(NetworkNode(
                id=outlet,
                label=outlet,
                type="outlet",
                size=outlet_report_count.get(outlet, 1),
            ))

    # Build edges: outlets sharing narratives
    edges: list[NetworkEdge] = []
    outlets_list = sorted(outlet_ids)
    for i, a in enumerate(outlets_list):
        for b in outlets_list[i + 1:]:
            shared = outlet_narratives[a] & outlet_narratives[b]
            if shared:
                edges.append(NetworkEdge(
                    source=a,
                    target=b,
                    weight=len(shared),
                    label=f"{len(shared)} shared narratives",
                ))

    # Also add narrative nodes for context (top 10 most connected)
    from collections import Counter
    all_narr_ids = Counter()
    for narrs in outlet_narratives.values():
        all_narr_ids.update(narrs)

    # Get narrative names
    narr_names: dict[str, str] = {}
    all_matches = db.query(NarrativeMatch).all()
    for m in all_matches:
        narr_names[m.narrative_id] = m.narrative_name

    for narr_id, count in all_narr_ids.most_common(10):
        narr_node_id = f"narr:{narr_id}"
        nodes.append(NetworkNode(
            id=narr_node_id,
            label=narr_names.get(narr_id, narr_id),
            type="narrative",
            size=count,
            color="#f59e0b",
        ))
        # Connect narratives to their outlets
        for outlet in outlets_list:
            if narr_id in outlet_narratives.get(outlet, set()):
                edges.append(NetworkEdge(
                    source=outlet,
                    target=narr_node_id,
                    weight=1,
                ))

    return NetworkGraphResponse(nodes=nodes, edges=edges)


# ---------------------------------------------------------------------------
# Social Media Analysis endpoints (Sprint 3 integration)
# ---------------------------------------------------------------------------


class SocialMediaRunRequest(BaseModel):
    platform: str = Field(..., description="twitter or telegram")
    handle: str = Field(..., description="Account handle, e.g. @rt_com")


class SocialMediaStatusResponse(BaseModel):
    id: int
    platform: str
    handle: str
    status: str
    created_at: datetime
    message: Optional[str] = None


@app.post("/social-media/analyze", response_model=SocialMediaStatusResponse)
@limiter.limit("5/minute")
def create_social_media_run(
    request: Request,
    payload: SocialMediaRunRequest,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
):
    """Create a social media account analysis run.

    Requires platform API keys configured in environment:
    - Twitter: TWITTER_BEARER_TOKEN
    - Telegram: TELEGRAM_BOT_TOKEN
    """
    from src.cddbs.config import settings as _settings

    # Sanitize inputs (OWASP LLM01)
    clean_handle = sanitize_handle(payload.handle)
    platform = payload.platform
    if platform not in ("twitter", "telegram"):
        raise HTTPException(status_code=400, detail="Unsupported platform")

    # Check platform API key availability
    if platform == "twitter" and not _settings.TWITTER_BEARER_TOKEN:
        raise HTTPException(
            status_code=400,
            detail="Twitter API not configured",
        )
    if platform == "telegram" and not _settings.TELEGRAM_BOT_TOKEN:
        raise HTTPException(
            status_code=400,
            detail="Telegram API not configured",
        )

    # Create placeholder report
    report = Report(
        outlet=clean_handle,
        country="",
        final_report=None,
        data={
            "platform": platform,
            "handle": clean_handle,
            "status": "pending",
            "analysis_date": datetime.now(UTC).isoformat(),
        },
    )
    db.add(report)
    db.commit()
    db.refresh(report)

    background_tasks.add_task(
        _run_social_media_job,
        report_id=report.id,
        platform=platform,
        handle=clean_handle,
    )

    return SocialMediaStatusResponse(
        id=report.id,
        platform=platform,
        handle=clean_handle,
        status="queued",
        created_at=report.created_at,
        message="Social media analysis scheduled",
    )


def _run_social_media_job(
    report_id: int,
    platform: str,
    handle: str,
):
    """Background job for social media analysis."""
    import asyncio
    from src.cddbs.pipeline.social_media_pipeline import (
        run_social_media_pipeline,
        fetch_twitter_data,
        fetch_telegram_data,
    )

    db = SessionLocal()
    try:
        # Fetch platform data
        if platform == "twitter":
            raw_data = asyncio.run(fetch_twitter_data(handle))
        elif platform == "telegram":
            raw_data = asyncio.run(fetch_telegram_data(handle))
        else:
            raise ValueError(f"Unsupported platform: {platform}")

        run_social_media_pipeline(
            platform=platform,
            handle=handle,
            report_id=report_id,
            raw_data=raw_data,
        )

    except Exception as exc:
        report = db.query(Report).filter(Report.id == report_id).first()
        if report:
            report.data = {
                "platform": platform,
                "handle": handle,
                "status": "failed",
                "analysis_date": datetime.now(UTC).isoformat(),
                "errors": [str(exc)],
            }
            db.add(report)
            db.commit()
    finally:
        db.close()


@app.get("/api-status")
def api_status():
    """Check configuration status of external APIs."""
    from src.cddbs.config import settings as _settings

    status = {
        "serpapi": {
            "configured": bool(_settings.SERPAPI_KEY),
            "status": "configured" if _settings.SERPAPI_KEY else "not_configured",
            "message": "SerpAPI key is configured" if _settings.SERPAPI_KEY else "SerpAPI key not configured",
        },
        "gemini": {
            "configured": bool(_settings.GOOGLE_API_KEY),
            "status": "configured" if _settings.GOOGLE_API_KEY else "not_configured",
            "message": "Google API key is configured" if _settings.GOOGLE_API_KEY else "Google API key not configured",
        },
        "twitter": {
            "configured": bool(_settings.TWITTER_BEARER_TOKEN),
            "status": "configured" if _settings.TWITTER_BEARER_TOKEN else "not_configured",
            "message": "Twitter Bearer Token is configured" if _settings.TWITTER_BEARER_TOKEN else "TWITTER_BEARER_TOKEN not set",
        },
        "telegram": {
            "configured": bool(_settings.TELEGRAM_BOT_TOKEN),
            "status": "configured" if _settings.TELEGRAM_BOT_TOKEN else "not_configured",
            "message": "Telegram Bot Token is configured" if _settings.TELEGRAM_BOT_TOKEN else "TELEGRAM_BOT_TOKEN not set",
        },
    }

    return status


# ---------------------------------------------------------------------------
# JSON Export endpoint
# ---------------------------------------------------------------------------


@app.get("/analysis-runs/{report_id}/export")
def export_analysis_run(report_id: int, db: Session = Depends(get_db)):
    """Export a completed analysis run as a structured JSON download.

    Returns the full briefing data including quality scorecard, narrative
    matches, article analyses, and metadata — suitable for archiving or
    inter-system exchange.
    """
    report = db.query(Report).filter(Report.id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    status, msg = _get_report_status(report)
    data = report.data or {}

    # Structured briefing
    structured_briefing = None
    if isinstance(data, dict):
        structured_briefing = data.get("structured_briefing")
    if not structured_briefing and report.raw_response:
        try:
            import re as _re
            _json_match = _re.search(r'(\{.*\})', report.raw_response, _re.DOTALL)
            if _json_match:
                _parsed = json.loads(_json_match.group(1))
                structured_briefing = _parsed.get("structured_briefing")
        except Exception:
            pass

    # Quality scorecard
    briefing_row = db.query(Briefing).filter(Briefing.report_id == report_id).first()
    quality = None
    if briefing_row:
        quality = {
            "total_score": briefing_row.quality_score,
            "max_score": 70,
            "rating": briefing_row.quality_rating,
            "dimensions": briefing_row.quality_details.get("dimensions") if briefing_row.quality_details else None,
            "prompt_version": briefing_row.prompt_version,
        }

    # Narrative matches
    matches = db.query(NarrativeMatch).filter(
        NarrativeMatch.report_id == report_id
    ).order_by(NarrativeMatch.match_count.desc()).all()
    narratives = [
        {
            "narrative_id": m.narrative_id,
            "narrative_name": m.narrative_name,
            "category": m.category,
            "confidence": m.confidence,
            "matched_keywords": m.matched_keywords,
            "match_count": m.match_count,
        }
        for m in matches
    ]

    # Articles
    articles = [
        {
            "id": a.id,
            "title": a.title,
            "link": a.link,
            "snippet": a.snippet,
            "date": a.date,
            "analysis": a.meta.get("analysis") if isinstance(a.meta, dict) else None,
        }
        for a in report.articles
    ]

    export_payload = {
        "export_version": "1.0",
        "exported_at": datetime.now(UTC).isoformat(),
        "report": {
            "id": report.id,
            "outlet": report.outlet,
            "country": report.country,
            "created_at": report.created_at.isoformat() if report.created_at else None,
            "status": status,
            "meta": {
                "outlet": data.get("outlet", report.outlet) if isinstance(data, dict) else report.outlet,
                "url": data.get("url", "") if isinstance(data, dict) else "",
                "country": data.get("country", report.country or "") if isinstance(data, dict) else "",
                "analysis_date": data.get("analysis_date") if isinstance(data, dict) else None,
                "articles_analyzed": data.get("articles_analyzed", 0) if isinstance(data, dict) else 0,
            },
        },
        "final_report": report.final_report,
        "structured_briefing": structured_briefing,
        "quality": quality,
        "narrative_matches": narratives,
        "articles": articles,
    }

    filename = f"cddbs-export-{report.outlet.replace(' ', '_')}-{report.id}.json"
    return JSONResponse(
        content=export_payload,
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )


# ---------------------------------------------------------------------------
# Metrics endpoint (operational stats)
# ---------------------------------------------------------------------------


class MetricsResponse(BaseModel):
    total_analyses: int
    completed_analyses: int
    failed_analyses: int
    success_rate: Optional[float] = None
    avg_quality_score: Optional[float] = None
    avg_duration_seconds: Optional[float] = None
    total_narratives_matched: int
    total_articles_ingested: int
    active_event_clusters: int
    active_narrative_bursts: int
    top_countries: List[dict] = Field(default_factory=list)
    top_narratives: List[dict] = Field(default_factory=list)


@app.get("/metrics", response_model=MetricsResponse)
def get_metrics(db: Session = Depends(get_db)):
    """Operational metrics for the CDDBS platform.

    Returns success rate, average quality, throughput, and top-level
    breakdowns useful for monitoring and reporting.
    """
    from sqlalchemy import func

    reports = db.query(Report).all()
    total = len(reports)
    completed = 0
    failed = 0
    quality_scores = []
    durations = []
    country_counts: dict[str, int] = {}

    for r in reports:
        st, _ = _get_report_status(r)
        if st == "completed":
            completed += 1
        elif st == "failed":
            failed += 1

        rdata = r.data or {}
        if isinstance(rdata, dict) and rdata.get("quality_score"):
            quality_scores.append(rdata["quality_score"])

        # Estimate duration from creation to analysis_date
        if isinstance(rdata, dict) and rdata.get("analysis_date") and r.created_at:
            try:
                from datetime import timezone
                analysis_dt = datetime.fromisoformat(rdata["analysis_date"])
                if analysis_dt.tzinfo is None:
                    analysis_dt = analysis_dt.replace(tzinfo=timezone.utc)
                created = r.created_at
                if created.tzinfo is None:
                    created = created.replace(tzinfo=timezone.utc)
                diff = (analysis_dt - created).total_seconds()
                if 0 < diff < 3600:
                    durations.append(diff)
            except Exception:
                pass

        if r.country:
            country_counts[r.country] = country_counts.get(r.country, 0) + 1

    success_rate = round(completed / total * 100, 1) if total else None
    avg_quality = round(sum(quality_scores) / len(quality_scores), 1) if quality_scores else None
    avg_duration = round(sum(durations) / len(durations), 1) if durations else None

    total_narratives = db.query(func.count(NarrativeMatch.id)).scalar() or 0
    articles_ingested = db.query(func.count(RawArticle.id)).scalar() or 0
    active_events = db.query(func.count(EventCluster.id)).filter(EventCluster.status == "active").scalar() or 0
    active_bursts = db.query(func.count(NarrativeBurst.id)).filter(NarrativeBurst.resolved_at == None).scalar() or 0

    top_countries = sorted(
        [{"country": c, "count": n} for c, n in country_counts.items()],
        key=lambda x: x["count"], reverse=True,
    )[:10]

    # Top narratives
    from collections import defaultdict
    narr_totals: dict[str, dict] = defaultdict(lambda: {"name": "", "count": 0})
    for m in db.query(NarrativeMatch).all():
        narr_totals[m.narrative_id]["name"] = m.narrative_name
        narr_totals[m.narrative_id]["count"] += m.match_count
    top_narr = sorted(
        [{"narrative_id": nid, "name": d["name"], "total_matches": d["count"]}
         for nid, d in narr_totals.items()],
        key=lambda x: x["total_matches"], reverse=True,
    )[:10]

    return MetricsResponse(
        total_analyses=total,
        completed_analyses=completed,
        failed_analyses=failed,
        success_rate=success_rate,
        avg_quality_score=avg_quality,
        avg_duration_seconds=avg_duration,
        total_narratives_matched=total_narratives,
        total_articles_ingested=articles_ingested,
        active_event_clusters=active_events,
        active_narrative_bursts=active_bursts,
        top_countries=top_countries,
        top_narratives=top_narr,
    )


# ---------------------------------------------------------------------------
# Quality Trends endpoint (per-outlet quality over time)
# ---------------------------------------------------------------------------


class QualityTrendPoint(BaseModel):
    report_id: int
    outlet: str
    created_at: datetime
    quality_score: Optional[int] = None
    quality_rating: Optional[str] = None


class QualityTrendsResponse(BaseModel):
    trends: List[QualityTrendPoint]
    outlet_averages: dict  # {outlet: avg_score}


@app.get("/stats/quality-trends", response_model=QualityTrendsResponse)
def get_quality_trends(
    outlet: Optional[str] = None,
    limit: int = 100,
    db: Session = Depends(get_db),
):
    """Quality score trends over time, optionally filtered by outlet.

    Returns chronological quality data points and per-outlet averages,
    useful for tracking whether briefing quality is improving.
    """
    query = db.query(Report).join(Briefing, Briefing.report_id == Report.id)

    if outlet:
        query = query.filter(Report.outlet == outlet)

    reports = query.order_by(Report.created_at.desc()).limit(limit).all()

    points = []
    outlet_scores: dict[str, list[int]] = {}

    for r in reports:
        b = db.query(Briefing).filter(Briefing.report_id == r.id).first()
        if b:
            points.append(QualityTrendPoint(
                report_id=r.id,
                outlet=r.outlet,
                created_at=r.created_at,
                quality_score=b.quality_score,
                quality_rating=b.quality_rating,
            ))
            if b.quality_score is not None:
                outlet_scores.setdefault(r.outlet, []).append(b.quality_score)

    outlet_averages = {
        name: round(sum(scores) / len(scores), 1)
        for name, scores in outlet_scores.items()
        if scores
    }

    # Return in chronological order
    points.reverse()

    return QualityTrendsResponse(
        trends=points,
        outlet_averages=outlet_averages,
    )


# ---------------------------------------------------------------------------
# Sprint 6: Webhook Configuration Endpoints
# ---------------------------------------------------------------------------


class WebhookCreateRequest(BaseModel):
    url: str
    events: List[str] = Field(
        default_factory=lambda: ["pipeline_failure", "narrative_burst"]
    )
    secret: Optional[str] = None


class WebhookResponse(BaseModel):
    id: int
    url: str
    events: List[str] = Field(default_factory=list)
    active: bool
    created_at: datetime
    last_triggered_at: Optional[datetime] = None
    failure_count: int = 0

    model_config = {"from_attributes": True}


@app.post("/webhooks", response_model=WebhookResponse)
def create_webhook(
    payload: WebhookCreateRequest,
    db: Session = Depends(get_db),
):
    """Register a new webhook endpoint for alert delivery."""
    invalid = [e for e in payload.events if e not in SUPPORTED_EVENTS and e != "*"]
    if invalid:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid event types: {invalid}. Supported: {SUPPORTED_EVENTS}",
        )
    hook = WebhookConfig(
        url=payload.url,
        events=payload.events,
        secret=payload.secret,
        active=True,
    )
    db.add(hook)
    db.commit()
    db.refresh(hook)
    return hook


@app.get("/webhooks", response_model=List[WebhookResponse])
def list_webhooks(db: Session = Depends(get_db)):
    """List all webhook configurations."""
    return (
        db.query(WebhookConfig)
        .order_by(WebhookConfig.created_at.desc())
        .all()
    )


@app.delete("/webhooks/{webhook_id}")
def delete_webhook(webhook_id: int, db: Session = Depends(get_db)):
    """Deactivate a webhook (soft delete)."""
    hook = db.query(WebhookConfig).filter(WebhookConfig.id == webhook_id).first()
    if not hook:
        raise HTTPException(status_code=404, detail="Webhook not found")
    hook.active = False
    db.commit()
    return {"status": "deactivated", "id": webhook_id}


@app.post("/webhooks/test/{webhook_id}")
async def test_webhook(webhook_id: int, db: Session = Depends(get_db)):
    """Send a test pipeline_failure event to a webhook endpoint."""
    hook = db.query(WebhookConfig).filter(WebhookConfig.id == webhook_id).first()
    if not hook:
        raise HTTPException(status_code=404, detail="Webhook not found")
    delivered = await fire_event(
        "pipeline_failure",
        {"test": True, "message": "CDDBS webhook test event"},
        db_session=db,
    )
    return {"delivered": delivered, "webhook_id": webhook_id}


# ---------------------------------------------------------------------------
# Compliance Evidence Endpoint (Sprint 9)
# ---------------------------------------------------------------------------


@app.get("/compliance/evidence")
def get_compliance_evidence(db: Session = Depends(get_db)):
    """Machine-readable compliance evidence for EU AI Act / CRA auditing.

    Returns a snapshot of all implemented compliance measures, test counts,
    security controls, and AI provenance configuration.
    """
    total_reports = db.query(Report).count()
    total_briefings = db.query(Briefing).count()
    total_topic_runs = db.query(TopicRun).count()

    return {
        "system": "CDDBS",
        "version": "0.9.0",
        "generated_at": datetime.now(UTC).isoformat(),
        "ai_model": {
            "provider": "Google",
            "model_id": settings.GEMINI_MODEL,
            "type": "cloud_api",
            "fine_tuned": False,
        },
        "security_controls": {
            "cors_policy": "explicit_origins",
            "rate_limiting": True,
            "input_sanitization": True,
            "output_validation": True,
            "security_headers": True,
            "error_sanitization": True,
            "api_key_hygiene": "server_side_only",
        },
        "compliance_measures": {
            "eu_ai_act": {
                "art_50_transparency": "AIProvenanceCard + ai_metadata in API",
                "art_9_quality_management": "7-dimension quality scoring (70pt rubric)",
                "art_14_human_oversight": "Grounding score + ungrounded claim flagging",
                "art_12_record_keeping": "This endpoint + CI artifacts",
            },
            "cra": {
                "art_13_15_sbom": "CycloneDX SBOM generated in CI",
                "art_10_4_vulnerability_handling": "pip-audit + custom dependency scanner in CI",
            },
            "dsgvo": {
                "data_minimization": "No PII collected; analysis operates on public media data",
            },
        },
        "statistics": {
            "total_analyses": total_reports,
            "total_briefings": total_briefings,
            "total_topic_runs": total_topic_runs,
        },
    }
